<?php
/**
 * WPHEKA Framework registration entry point.
 *
 * ============================ FROZEN FILE ============================
 * Do not change this file. Ever. See ADR-001.
 *
 * A plugin loads the framework with one line in its main file, at include
 * time rather than on a hook:
 *
 *     require_once __DIR__ . '/framework/register.php';
 *
 * The version deliberately lives in version.php rather than here, so that this
 * file stays byte-identical across every framework release. version.php is
 * regenerated by the release tooling; this file never changes.
 *
 * @package WPHEKA\Framework
 */

defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'WPHEKA_Framework_Versions', false ) ) {
	require_once __DIR__ . '/registry.php';
}

WPHEKA_Framework_Versions::register(
	require __DIR__ . '/version.php',
	__DIR__ . '/bootstrap.php'
);
