<?php
/**
 * Version of this bundled framework build.
 *
 * Generated by scripts/bundle-framework.sh — do not edit by hand.
 *
 * @package WPHEKA\Framework
 */

defined( 'ABSPATH' ) || exit;

return '1.0.0';
